#!/bin/bash
# Author: Cristián Maureira
# Last update: 16.06.2014

directory_path="/sys/class/backlight/intel_backlight"
actual=$(cat $directory_path/actual_brightness)
maximum=$(cat $directory_path/max_brightness)
unit=$(( 5 * $maximum / 100 ))

if [[ $1 == "+" ]];then
    new=$(( $actual + $unit ))
    if [[ $new -gt $maximum ]];then
        new=$maximum
    fi
    sudo bash -c "echo $new > $directory_path/brightness"

else if [[ $1 == "" ]];then
    echo $(( $actual * 100 / $maximum ))

    else if [[ $1 == "-" ]];then
            new=$(($actual-$unit))
            if [[ $new -lt 0 ]];then
                new=0
            fi
            sudo bash -c "echo $new > $directory_path/brightness"

            else
                echo "[ERROR] Invalid option"
                echo "Use it with a plus or minus sign"
                echo "$ brightness +/-"
        fi
    fi
fi
#sudo bash -c "echo 100 > /sys/class/backlight/acpi_video0/brightness"
