#!/bin/bash

#ffmpeg -framerate 20 -i xy_%04d.png -c:v libx264 -r 30 -pix_fmt yuv420p out.mp4
#ffmpeg -framerate 20 -i splash_%04d.png -c:v libx264 -r 30 -pix_fmt yuv420p out.mp4
#ffmpeg -framerate 20 -i splash_dx_%04d.png -c:v libx264 -r 30 -pix_fmt yuv420p out.mp4
#ffmpeg -framerate 20 -i fig_%04d.png -c:v libx264 -r 30 -pix_fmt yuv420p out.mp4
#ffmpeg -framerate 12 -i join_%04d.png -c:v libx264 -r 30 -pix_fmt yuv420p out.mp4
ffmpeg -framerate 20 -i join_r10_%05d.png -c:v libx264 -r 30 -pix_fmt yuv420p out.mp4
#ffmpeg -framerate 12 -i F0p0_join_%04d.png -c:v libx264 -r 30 -pix_fmt yuv420p out.mp4
#ffmpeg -framerate 12 -i F0p5_join_%04d.png -c:v libx264 -r 30 -pix_fmt yuv420p F0p5.mp4
#ffmpeg -framerate 12 -i F1p0_join_%04d.png -c:v libx264 -r 30 -pix_fmt yuv420p F1p0.mp4
#ffmpeg -framerate 20 -i new_%05d.png -c:v libx264 -r 30 -pix_fmt yuv420p out.mp4
#ffmpeg -framerate 20 -i splash_xy_%03d.png -c:v libx264 -r 30 -pix_fmt yuv420p out.mp4
