#!/bin/bash

#out=$(awk -F"[][]" '/%/ { print $2 }' <(amixer sget Master) | head -n 1)
current=$(pamixer --get-volume)

re='^[0-9]+$'

if [[ $1 == "" ]];then
    echo $current
elif [[ $1 == "+" ]];then
    pamixer -i 5
elif [[ $1 == "-" ]];then
    pamixer -d 5
elif [[ $1 == "m" ]];then
    pamixer -t
elif [[ $1 == "p" ]];then
    pacmd suspend 1
fi

